// <auto-generated />
using System;
using BookSharingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookSharingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250226114644_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookSharingApp.Models.ClubModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "",
                            Logo = "default.jpg",
                            Name = "Book Club",
                            UpdatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "",
                            Logo = "default.jpg",
                            Name = "Magazine Club",
                            UpdatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified),
                            IsActive = true,
                            Location = "Badmosh",
                            Logo = "default.jpg",
                            Name = "Paper Club",
                            UpdatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BookSharingApp.Models.ClubUsersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ClubId", "UserId")
                        .IsUnique();

                    b.ToTable("ClubUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            CreatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified),
                            IsActive = true,
                            Role = "admin",
                            UpdatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 2,
                            CreatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified),
                            IsActive = true,
                            Role = "admin",
                            UpdatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ClubId = 3,
                            CreatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified),
                            IsActive = true,
                            Role = "clubadmin",
                            UpdatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BookSharingApp.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogIn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MFA")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified),
                            Email = "sarthak.vadgama.hs@gmail.com",
                            IsActive = true,
                            MFA = true,
                            Mobile = "+91 8989258867",
                            Name = "Admin",
                            Password = "admin",
                            Points = 0,
                            Profile = "default.jpg",
                            ResetToken = "",
                            UpdatedAt = new DateTime(2025, 2, 21, 10, 35, 14, 370, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BookSharingApp.Models.ClubUsersModel", b =>
                {
                    b.HasOne("BookSharingApp.Models.ClubModel", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookSharingApp.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
